config/routes.rb
require 'sidekiq/web'

AutoCommish::Application.routes.draw do
  root 'leagues#index'
  resources :leagues, only: [:index, :new, :create, :show] do

    member do
      get :send_update
    end

    collection do
      get :send_text_reminders
    end

    resources :players, only: [:new, :show, :create, :edit, :update] do

      member do
        get :send_text
      end

      resources :transactions, only: [:new, :create]
    end
  end

  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/league.rb
class League < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: {case_sensitive: true}
  validates :fee, presence: true
  validates_numericality_of :fee, greater_than: 0
  has_many :players, -> {includes :player_balance }

  def gms_who_won
    @gms_who_won ||= players.select do |player|
      player.player_balance.balance > 0
    end.sort_by{|p| p.balance}.reverse
  end

  def gms_who_paid
    @gms_who_paid ||= players.select do |player|
      player.player_balance.balance == 0
    end.sort_by{|p| p.balance}.reverse
  end

  def gms_who_owe
    @gms_who_owe ||= players.select do |player|
      player.player_balance.balance < 0
    end.sort_by{|p| p.balance}.reverse
  end

end

app/models/message.rb
class Message

  attr_reader :player

  def initialize(player)
    @player = player
  end


  def send_text_reminder
    number_to_send_to = player.phone

    twilio_sid = ENV["TWILIO_SID"]
    twilio_token = ENV["TWILIO_TOKEN"]
    twilio_phone_number = "12402930574"

    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token

    @twilio_client.account.sms.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number_to_send_to,
      :body => "This is reminder that you currently owe $#{-player.balance} for 2012-2013 #{player.league.name} Fantasy Basketball Season, please make your payment as soon as possible")
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base

  before_create :convert_amount_to_cents

  def amount_in_dollars
    amount.to_f / 100 if amount
  end

  private

  def convert_amount_to_cents
    self.amount = amount.to_f * 100 if amount.present?
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  after_create :set_initial_player_balance

  belongs_to :league
  has_one :player_balance

  validates :full_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: {case_sensitive: true}

  validates :phone, presence: true
  validates :phone, uniqueness: true

  validates :league_id, presence: true


  def balance
    @balance ||= player_balance.balance_in_dollars
  end

  private

  def set_initial_player_balance
    PlayerBalance.create(balance: -league.fee, player_id: self.id)
  end
end

app/models/player_balance.rb
class PlayerBalance < ActiveRecord::Base
  belongs_to :player
  has_many :payments

  before_create :convert_balance_to_cents

  def balance_in_dollars
    balance.to_f / 100 if balance
  end

  def update_balance(balance)
    update_column(:balance, balance.to_f * 100)
  end

  private

  def convert_balance_to_cents
    self.balance = balance.to_f * 100 if balance.present?
  end
end

app/models/transaction.rb
class Transaction

  def initialize(player)
    @player = player
  end

  def update_balance(amount)
    new_balance = @player.balance + amount

    if @player.player_balance.update_balance(new_balance)
      @player.player_balance.payments.create(amount: amount)
    else
      false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def index
    @leagues = League.all
  end

  def show
    @league = League.find(params[:id])
  end

  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)

    if @league.save
      redirect_to @league, notice: "League was successfully created"
    else
      flash.now[:alert] = "League could not be saved"
      render :new
    end
  end

  def send_update
    league = League.find(params[:id])
    EmailWorker.perform_async(league.id)
    redirect_to league, notice: "Payment update was sent"
  end

  def send_text_reminders
    TextMessageWorker.perform_async
    redirect_to leagues_path, notice: "Text messages were sent"
  end

  private

  def league_params
    params.require(:league).permit(:name, :fee)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :find_player, only: [:show, :edit, :send_text, :update]

  def show
    @league = @player.league
    @payments = @player.player_balance.payments
  end

  def new
    @league = League.find(params[:league_id])
    @player = Player.new
  end

  def create
    @league = League.find(params[:league_id])
    @player = @league.players.build(player_params)

    if @player.save
      redirect_to @player.league, notice: "Player was added"
    else
      flash.now[:alert] = "Player could not be added"
      render :new
    end
  end

  def edit
    @league = @player.league
  end

  def update
    if @player.update(player_params)
      redirect_to @player.league, notice: "Player was successfully updated"
    end
  end

  def send_text
    Message.new(@player).send_text_reminder
    redirect_to @player.league, notice: "Text was successfully sent"
  end


  private

  def player_params
    params.require(:player).permit(:full_name, :email, :phone, :league_id)
  end

  def find_player
    @player = Player.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index

  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :get_player, only: [:new, :create]

  def new
    @league = @player.league
  end

  def create
    if Transaction.new(@player).update_balance(params[:amount].to_i)
      redirect_to league_player_path(@player.league, @player), notice: "Payment successfully recorded"
    end
  end

  private

  def get_player
    @player = Player.find(params[:player_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "AutoCommish", root_path, :class => 'brand'

-# %ul.nav
-#   - if user_signed_in?
-#     %li
-#       = link_to 'Logout', destroy_user_session_path, :method=>'delete'
-#   - else
-#     %li
-#       = link_to 'Login', new_user_session_path
-#   - if user_signed_in?
-#     %li
-#       = link_to 'Edit account', edit_user_registration_path
-#   - else
-#     %li
-#       = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "AutoCommish"
    %meta{:content => content_for?(:description) ? yield(:description) : "App_Name", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    %link{:href=>"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css", :rel => "stylesheet"}
    %link{:href=>"//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css", :rel => "stylesheet"}
    = javascript_include_tag :application
    %script{:src=>"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"}
    %script{:src=>"//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"}
    %script{:src=>"//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.min.js"}
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      %nav.navbar-inner
        .container-fluid
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container-fluid
        .content
          = render 'layouts/messages'
          = yield
          %footer

app/views/leagues/_league.html.haml
%tr
  %td= link_to league.name, league_path(league)
  %td= number_to_currency league.fee

app/views/leagues/_player.html.haml
%tr
  %td= link_to player.full_name, league_player_path(player.league, player)
  %td= player.email
  %td= player.phone
  %td= number_to_currency player.balance
  %td
    = link_to "edit", edit_league_player_path(player.league, player), id: "player-#{player.id}"
    |
    = link_to "send text", send_text_league_player_path(player.league, player)

app/views/leagues/index.html.haml
.row-fluid
  .span6
    %h1 Leagues
    = link_to "Send Text Reminders to Delinquent GMs", send_text_reminders_leagues_path
    %br
    %br
    %table.table.table-striped.table-bordered
      %thead
        %tr
          %th League Name
          %th League Fee
      %tbody
        = render @leagues

    = link_to "Add League", new_league_path(@league)

app/views/leagues/new.html.haml
%h2 Create New League

= form_for @league, html: {class: 'form'}  do |f|
  %fieldset
    = f.label :name, "League Name"
    = f.text_field :name

    = f.label :fee, "League Fee"
    = f.text_field :fee
    .actions
      = f.submit "Create League", class: "btn btn-primary"

:javascript
  $(function(){
    $("#new_league").validate({
      debug:true,

      submitHandler: function(form){
        form.submit();
      },

      rules: {
        "league[name]": {required: true}
      }
    });
  });

app/views/leagues/show.html.haml
.row-fluid
  .span8
    %h1= @league.name

    %h3 General Managers
    %br
    = link_to "Send League Update", send_update_league_path(@league)
    %br
    %table.table.table-striped.table-bordered
      %thead
        %tr
          %th Name
          %th Email
          %th Phone
          %th Balance
          %th Action
      %tbody
        = render partial: "player", collection: @league.players, as: :player

    = link_to "Add General Manager", new_league_player_path(@league)

app/views/players/_form.html.haml
= form_for ([@league, @player]), html: {class: 'form'}  do |f|
  %fieldset
    = f.label :full_name, "Full Name"
    = f.text_field :full_name
    %br
    = f.label :email, "Email Address"
    = f.text_field :email
    %br
    = f.label :phone, "Mobile Phone"
    = f.text_field :phone
    %br
    .actions
      = f.submit "Save", class: "btn btn-primary"

app/views/players/_payment.html.haml
%tr
  %td= number_to_currency payment.amount_in_dollars
  %td #{time_ago_in_words(payment.created_at)} ago

app/views/players/edit.html.haml
%h1 Edit Player

%h2 Add New Player

= render 'form'
:javascript
  $(function(){
    $("#edit_player_#{@player.id}").validate({
      debug:true,

      submitHandler: function(form){
        form.submit();
      },

      rules: {
        "player[full_name]" : {required: true},
        "player[email]"     : {required: true, email: true},
        "player[phone]"     : {required: true, phoneUS: true},
        "player[balance]"   : {required: true, digits: true}
      }
    });
  });

app/views/players/new.html.haml
%h1= @league.name

%h2 Add New Player

= render 'form'

:javascript
  $(function(){
    $("#new_player").validate({
      debug:true,

      focusInvalid: false,
      submitHandler: function(form){
        form.submit();
      },

      rules: {
        "player[full_name]" : {required: true},
        "player[email]"     : {required: true, email: true},
        "player[phone]"     : {required: true, phoneUS: true},
        "player[balance]"   : {required: true, digits: true}
      }
    });
  });

app/views/players/show.html.haml
.row-fluid
  .span8
    %h1= link_to @league.name, league_path(@league)
    %h2 General Manager:  #{@player.full_name}
    %h3.balance Current Balance: #{number_to_currency @player.balance}

    = link_to "Record Payment", new_league_player_transaction_path(@league, @player)
    %br
    %br

    %table.table.table-bordered.table-striped.payments-table
      %thead
        %tr
          %th Amount
          %th Date
      %tbody
        = render partial: "payment", collection: @payments, as: :payment

app/views/static_pages/index.html.haml
%h1 Yo

app/views/transactions/new.html.haml
.row-fluid
  .span8
    %h1= link_to @league.name, league_path(@league)
    %h3
      Record Payment for 
      = link_to @player.full_name, league_player_path(@league, @player)
    %h4 Current Balance: #{number_to_currency @player.balance}

    = form_tag league_player_transactions_path(@league, @player), class: "form-inline" do
      = text_field_tag 'amount', nil, :id => "payment-amount"
      = submit_tag "Record Payment", class: "btn btn-primary"